[package]
name = "irl-cli"
version = "0.1.0"
authors = ["Citruspress <simon.hemaker@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irl = { path = "../irl" }
clap = "2.33.0"
main_error = "0.1.0"
